using System.Globalization;
using System.Linq;
using Content.Shared.HL.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._HL.Administration;

[GenerateTypedNameReferences]
public sealed partial class SubtleMessageWindow : DefaultWindow
{
    private const int MaxRecentColors = 5;
    private static readonly List<string> RecentColors = new();

    private readonly List<SubtleMessagePlayer> _allPlayers = new();
    private bool _initializedFromState;
    private (float X, float Y)? _userCoordinates;

    public SubtleMessageWindow()
    {
        RobustXamlLoader.Load(this);

        Players.SelectMode = ItemList.ItemListSelectMode.Multiple;
        PopupMessage.Placeholder = new Rope.Leaf("A mysterious voice whispers...");

        PlayerSearch.OnTextChanged += _ => RebuildPlayerList();
        DisplayToAll.OnPressed += _ => UpdatePlayerListEnabled();
        AnchorToRecipients.OnPressed += _ => UpdateCoordinateControls();
        UseRecipientOffset.OnPressed += _ => UpdateCoordinateControls();
        Wiggle.OnPressed += _ => UpdateWiggleControls();
        ColorHex.OnTextChanged += _ => UpdateColorPreview();
        UseCurrentPosition.OnPressed += _ => SetCoordinatesToUserPosition();

        AddPreset("Ominous", "#b30000", false, true, 2.2f, 4.5f, 3f, 4.5f, 1.1f);
        AddPreset("Urgent", "#e62424", false, false, 9f, 2f, 18f, 2f, 1.2f);
        AddPreset("Divine", "#fff3b0", true, true, 1.5f, 2f, 7f, 5.5f, 1.15f);

        UpdateWiggleControls();
        UpdatePlayerListEnabled();
        UpdateCoordinateControls();
        UpdateColorPreview();
        RebuildSwatches();
    }

    public void SetState(SubtleMessageEuiState state)
    {
        _allPlayers.Clear();
        _allPlayers.AddRange(state.Players);
        RebuildPlayerList(state.SelectedPlayer);

        _userCoordinates = state.HasUserCoordinates
            ? (state.UserX, state.UserY)
            : null;
        UpdateCoordinateControls();

        if (_initializedFromState)
            return;

        if (state.HasDefaultCoordinates)
        {
            XCoord.Text = state.DefaultX.ToString("0.##", CultureInfo.InvariantCulture);
            YCoord.Text = state.DefaultY.ToString("0.##", CultureInfo.InvariantCulture);
        }

        _initializedFromState = true;
    }

    public SubtleMessageRequest BuildRequest()
    {
        var request = new SubtleMessageRequest
        {
            PopupMessage = Rope.Collapse(PopupMessage.TextRope),
            ChatMessage = ChatMessage.Text,
            Recipients = GetSelectedPlayers(),
            DisplayToAll = DisplayToAll.Pressed,
            SendChat = SendChat.Pressed,
            Preview = Preview.Pressed,
            CloseAfter = !KeepOpen.Pressed,
            UseCoordinates = UseCoordinates.Pressed
                             && TryParseFloat(XCoord.Text, out _)
                             && TryParseFloat(YCoord.Text, out _),
            AnchorToRecipients = AnchorToRecipients.Pressed,
            UseRecipientOffset = UseRecipientOffset.Pressed,
            X = ParseFloat(XCoord.Text, 0f),
            Y = ParseFloat(YCoord.Text, 0f),
            Style = new SubtlePopupStyle
            {
                ColorHex = ColorHex.Text,
                Rainbow = Rainbow.Pressed,
                Wiggle = Wiggle.Pressed,
                WaveSpeed = ParseFloat(WaveSpeed.Text, 3f),
                WaveHeight = ParseFloat(WaveHeight.Text, 3f),
                CharactersPerSecond = ParseFloat(RevealSpeed.Text, 5f),
                Scale = ParseFloat(Scale.Text, 1f),
                LingerTime = ParseFloat(LingerTime.Text, 4f),
            },
        };

        RememberColor(request.Style.ColorHex);
        return request;
    }

    private void RebuildPlayerList(NetUserId? selectedPlayer = null)
    {
        var selected = GetSelectedPlayers().ToHashSet();
        if (selectedPlayer != null)
            selected.Add(selectedPlayer.Value);

        var search = PlayerSearch.Text.Trim();
        Players.Clear();

        foreach (var player in _allPlayers)
        {
            if (search.Length > 0 && !player.Username.Contains(search, StringComparison.OrdinalIgnoreCase))
                continue;

            var item = Players.AddItem(player.Username, metadata: player.UserId);
            item.Selected = selected.Contains(player.UserId);
        }
    }

    private List<NetUserId> GetSelectedPlayers()
    {
        return Players.GetSelected()
            .Select(item => item.Metadata)
            .OfType<NetUserId>()
            .ToList();
    }

    private void RebuildSwatches()
    {
        Swatches.RemoveAllChildren();

        foreach (var color in RecentColors)
            AddSwatch(color);
    }

    private void AddSwatch(string color)
    {
        var button = new Button
        {
            Text = string.Empty,
            MinWidth = 24,
            MaxWidth = 24,
            MinHeight = 22,
            ModulateSelfOverride = Color.FromHex(color),
            ToolTip = color,
        };

        button.OnPressed += _ =>
        {
            ColorHex.Text = color;
            UpdateColorPreview();
        };

        Swatches.AddChild(button);
    }

    private void AddPreset(
        string name,
        string color,
        bool rainbow,
        bool wiggle,
        float waveSpeed,
        float waveHeight,
        float revealSpeed,
        float linger,
        float scale)
    {
        var button = new Button
        {
            Text = name,
            MinWidth = 72,
        };

        button.OnPressed += _ =>
        {
            ColorHex.Text = color;
            Rainbow.Pressed = rainbow;
            Wiggle.Pressed = wiggle;
            WaveSpeed.Text = waveSpeed.ToString("0.##", CultureInfo.InvariantCulture);
            WaveHeight.Text = waveHeight.ToString("0.##", CultureInfo.InvariantCulture);
            RevealSpeed.Text = revealSpeed.ToString("0.##", CultureInfo.InvariantCulture);
            LingerTime.Text = linger.ToString("0.##", CultureInfo.InvariantCulture);
            Scale.Text = scale.ToString("0.##", CultureInfo.InvariantCulture);
            UpdateWiggleControls();
            UpdateColorPreview();
        };

        Presets.AddChild(button);
    }

    private void RememberColor(string colorText)
    {
        if (!TryNormalizeColor(colorText, out var color))
            return;

        RecentColors.RemoveAll(existing => string.Equals(existing, color, StringComparison.OrdinalIgnoreCase));
        RecentColors.Insert(0, color);

        if (RecentColors.Count > MaxRecentColors)
            RecentColors.RemoveRange(MaxRecentColors, RecentColors.Count - MaxRecentColors);

        RebuildSwatches();
    }

    private void UpdateWiggleControls()
    {
        WaveSpeedLabel.Visible = Wiggle.Pressed;
        WaveSpeed.Visible = Wiggle.Pressed;
        WaveHeightLabel.Visible = Wiggle.Pressed;
        WaveHeight.Visible = Wiggle.Pressed;
    }

    private void UpdatePlayerListEnabled()
    {
        Players.SelectMode = DisplayToAll.Pressed
            ? ItemList.ItemListSelectMode.None
            : ItemList.ItemListSelectMode.Multiple;
        Players.ModulateSelfOverride = DisplayToAll.Pressed ? Color.Gray : null;
    }

    private void UpdateCoordinateControls()
    {
        UseRecipientOffset.Disabled = !AnchorToRecipients.Pressed;
        if (!AnchorToRecipients.Pressed)
            UseRecipientOffset.Pressed = false;

        var usingOffset = AnchorToRecipients.Pressed && UseRecipientOffset.Pressed;
        XCoordLabel.Text = usingOffset ? "Offset X" : "X";
        YCoordLabel.Text = usingOffset ? "Offset Y" : "Y";
        UseCurrentPosition.Disabled = _userCoordinates == null || usingOffset;

        if (AnchorToRecipients.Pressed && !UseRecipientOffset.Pressed)
        {
            XCoord.ModulateSelfOverride = Color.Gray;
            YCoord.ModulateSelfOverride = Color.Gray;
        }
        else
        {
            XCoord.ModulateSelfOverride = null;
            YCoord.ModulateSelfOverride = null;
        }
    }

    private void UpdateColorPreview()
    {
        if (TryNormalizeColor(ColorHex.Text, out var color))
        {
            ColorPreview.FontColorOverride = Color.FromHex(color);
        }
        else
        {
            ColorPreview.FontColorOverride = Color.Red;
        }
    }

    private void SetCoordinatesToUserPosition()
    {
        if (_userCoordinates == null || AnchorToRecipients.Pressed && UseRecipientOffset.Pressed)
            return;

        XCoord.Text = _userCoordinates.Value.X.ToString("0.##", CultureInfo.InvariantCulture);
        YCoord.Text = _userCoordinates.Value.Y.ToString("0.##", CultureInfo.InvariantCulture);
    }

    private static bool TryNormalizeColor(string text, out string color)
    {
        try
        {
            color = Color.FromHex(text).ToHex();
            return true;
        }
        catch (Exception)
        {
            color = string.Empty;
            return false;
        }
    }

    private static float ParseFloat(string text, float fallback)
    {
        return TryParseFloat(text, out var value) ? value : fallback;
    }

    private static bool TryParseFloat(string text, out float value)
    {
        return float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
    }
}
