using System.Numerics;
using Content.Shared.CCVar;
using Content.Shared.Ghost.Roles; // Hardlight
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleRulesWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfg = IoCManager.Resolve<IConfigurationManager>();
        private float _timer;
        private readonly float _ghostRoleTime; // Hardlight
        private string _currentRules; // Hardlight
        public string? SelectedChoiceId { get; private set; } // Hardlight

        public GhostRoleRulesWindow(string rules, Action<BaseButton.ButtonEventArgs> requestAction, IReadOnlyList<GhostRoleChoiceInfo>? choices = null) // Hardlight: GhostRoleChoiceInfo
        {
            RobustXamlLoader.Load(this);
            var ghostRoleTime = _cfg.GetCVar(CCVars.GhostRoleTime);
            _timer = ghostRoleTime;
            _ghostRoleTime = ghostRoleTime; // Hardlight
            _currentRules = rules; // Hardlight

            if (ghostRoleTime > 0f)
            {
                RequestButton.Text = Loc.GetString("ghost-roles-window-request-role-button-timer", ("time", $"{_timer:0.0}"));
                // TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(rules + "\n" + Loc.GetString("ghost-roles-window-rules-footer", ("time", ghostRoleTime))));
                RequestButton.Disabled = true;
            }

            // Hardlight start
            if (choices is { Count: > 0 })
            {
                ChoiceButtonContainer.Visible = true;

                foreach (var choice in choices)
                {
                    var button = new Button
                    {
                        Text = choice.Name,
                        TextAlign = Label.AlignMode.Center,
                        MinSize = new Vector2(120, 28),
                    };

                    button.OnPressed += _ => SelectChoice(choice);
                    ChoiceButtonContainer.AddChild(button);
                }

                SelectChoice(choices[0]);
            }
            else
            {
                UpdateRulesText();
            }

            RequestButton.OnPressed += requestAction;
        }

        private void SelectChoice(GhostRoleChoiceInfo choice)
        {
            SelectedChoiceId = choice.Id;
            _currentRules = $"{choice.Description}\n\n{choice.Rules}";
            UpdateRulesText();
        }

        private void UpdateRulesText()
        {
            if (_ghostRoleTime > 0f)
            {
                TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(_currentRules + "\n" + Loc.GetString("ghost-roles-window-rules-footer", ("time", _ghostRoleTime))));
                return;
            }

            TopBanner.SetMessage(FormattedMessage.FromMarkupPermissive(_currentRules));
        }
        // Hardlight end


        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            if (!RequestButton.Disabled) return;
            if (_timer > 0.0)
            {
                _timer -= args.DeltaSeconds;
                RequestButton.Text = Loc.GetString("ghost-roles-window-request-role-button-timer", ("time", $"{_timer:0.0}"));
            }
            else
            {
                RequestButton.Disabled = false;
                RequestButton.Text = Loc.GetString("ghost-roles-window-request-role-button");
            }
        }
    }
}
